#pragma once

#include <array>
#include <cstdint>
#include <limits>
#include <optional>
#include <random>
#include <vector>

#include "uav_navigation_core/mppi/cost_evaluator.hpp"
#include "uav_navigation_core/trajectory_safety_checker.hpp"

namespace uav_navigation_core::mppi {

struct MppiOptimizerConfig {
  double lambda{1.0};
  std::array<double, 4> noise_sigma{{0.8, 0.8, 0.3, 0.3}};
  std::array<double, 4> minimum{{-2.0, -2.0, -1.0, -0.6}};
  std::array<double, 4> maximum{{2.0, 2.0, 1.0, 0.6}};
};

// Diagnostic classification of the family that produced one candidate sample.
// Gaussian samples are generated by the baseline sampler. The specific-action
// index is the zero/hold sequence prepended by BuildRecoveryProposals. The
// remaining families are emitted by the proactive proposal builder. A proposal
// whose target speed is below the current horizontal speed is classified as a
// braking proposal; otherwise it is classified as a recovery proposal.
enum class ProposalSource : std::size_t {
  kGaussian = 0,
  kReferenceProposal,
  kBrakingProposal,
  kRecoveryProposal,
  kSpecificAction,
  kCount,
};

// Deterministic rejection policy: a rejected sample is attributed to the first
// safety predicate that failed, mirroring the order the safety checker already
// evaluates them (swept cloud collision, known-map collision, then predicted
// stopping clearance). Samples are never double counted.
enum class RejectionReason {
  kSafe = 0,
  kNonFinite,
  kSweptCollision,
  kStaticCollision,
  kDynamicCollision,
  kStoppingDistance,
  kOther,
};

struct RejectionCounts {
  std::size_t total{0};
  std::size_t safe{0};
  std::size_t reject_non_finite{0};
  std::size_t reject_swept_collision{0};
  std::size_t reject_static_collision{0};
  // Reserved: the current obstacle representation has no dynamic/static
  // classifier, so this counter is always zero. It exists so a future
  // classifier can populate it without changing the diagnostic schema.
  std::size_t reject_dynamic_collision{0};
  std::size_t reject_stopping_distance{0};
  std::size_t reject_other{0};
};

struct ProposalSourceStats {
  std::size_t generated{0};
  std::size_t safe{0};
  double best_cost{std::numeric_limits<double>::infinity()};
};

struct MppiOptimizationResult {
  double rollout_time_ms{0.0};
  double cost_time_ms{0.0};
  double safety_time_ms{0.0};
  ControlSequence shifted_nominal{};
  ControlBatch perturbed_actions{};
  ControlBatch effective_noise{};
  std::vector<MppiTrajectory> trajectories{};
  std::vector<CostBreakdown> cost_breakdowns{};
  std::vector<double> rollout_costs{};
  std::vector<double> perturbation_costs{};
  std::vector<double> total_costs{};
  std::vector<double> weights{};
  std::vector<bool> safe{};
  ControlSequence updated_nominal{};
  Control first_command{};

  // M7.3 root-cause diagnostics. These fields never influence the selected
  // command; they only explain why samples were accepted or rejected.
  std::vector<RejectionReason> rejection_reasons{};
  std::vector<ProposalSource> sample_sources{};
  RejectionCounts rejection_counts{};
  std::array<ProposalSourceStats,
             static_cast<std::size_t>(ProposalSource::kCount)>
      proposal_source_stats{};
};

class GaussianNoiseSampler {
public:
  GaussianNoiseSampler(std::array<double, 4> standard_deviation,
                       std::uint64_t seed);
  ControlBatch Sample(std::size_t samples, std::size_t horizon);

private:
  std::array<double, 4> standard_deviation_;
  std::mt19937_64 engine_;
  std::normal_distribution<double> standard_normal_{0.0, 1.0};
};

class MppiOptimizer {
public:
  explicit MppiOptimizer(MppiOptimizerConfig config = {});

  MppiOptimizationResult OptimizeInjected(
      const IMotionModel &model, const CostEvaluator &cost_evaluator,
      const CostContext &cost_context, const MppiState &initial_state,
      const ControlSequence &nominal_before_shift, const Control &tail_control,
      const ControlBatch &injected_noise, double dt_s,
      const ControlBatch &specific_actions = {},
      const TrajectorySafetyChecker *safety_checker = nullptr,
      const ObstacleMap *safety_obstacles = nullptr,
      const std::vector<ProposalSource> *proposal_sources = nullptr) const;

  const MppiOptimizerConfig &config() const { return config_; }

private:
  MppiOptimizerConfig config_;
};

struct RecoveryProposalConfig {
  std::size_t horizon{0};
  std::size_t max_samples{0};
  double dt_s{0.1};
  double reference_speed_m_s{10.0};
  std::array<double, 4> minimum{{-10.0, -10.0, -0.6, -0.6}};
  std::array<double, 4> maximum{{10.0, 10.0, 0.6, 0.6}};
  bool proactive{false};
  bool rejection_recovery{false};
};

ControlBatch BuildRecoveryProposals(const PathReference *reference_path,
                                    double path_progress_m,
                                    double initial_horizontal_speed_m_s,
                                    const RecoveryProposalConfig &config);

struct RecoveryProposals {
  ControlBatch proposals{};
  std::vector<ProposalSource> sources{};
};

// Same proposal family as BuildRecoveryProposals, but also returns the source
// label of every sequence so diagnostics can account for feasibility per
// family. The proposal contents are byte-for-byte identical.
RecoveryProposals BuildRecoveryProposalsWithSources(
    const PathReference *reference_path, double path_progress_m,
    double initial_horizontal_speed_m_s, const RecoveryProposalConfig &config);

} // namespace uav_navigation_core::mppi
